### PR TITLE
test: add additional fixtures and tests for irp

### PR DESCRIPTION
**Pull request by MylesBorins**
was testing implementation locally to wrap head around new behavior. Here are the tests.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
FYI @guybedford and I are working on [this branch](https://github.com/GeoffreyBooth/ecmascript-modules/tree/mismatched-type-flag-and-package-scope) that adds a bunch of error messages and tests for `--type` and `package.json` `type:`, so you might not want to work on tests for those if you haven’t started yet.

**Comment by MylesBorins** [comment]
I've rebased off of modules-lkgr and changed the names to be more descriptive than `irp`

@GeoffreyBooth @guybedford can one of you sign off and land please?

**Comment by guybedford** [comment]
I've gone ahead and merged these tests now. Much appreciated @MylesBorins.

**Comment by GeoffreyBooth** [comment]
Whoops just caught a typo, one of the filenames has `irp` in it. Can we just push that rename onto `modules-lkgr`?

**Comment by MylesBorins** [comment]
Force pushed the branch with the fix in 6c03eed509

**Pull request merged**
