### PR TITLE
CI fixes for latest commits and reland #45

### PR DESCRIPTION
**Pull request by guybedford**
This fixes up some linting issues that crept in on the last merges.

### CODE REVIEW

**Comment by guybedford** [comment]
CI: https://ci.nodejs.org/job/node-test-commit/26361/

**Comment by MylesBorins** [comment]
Some failures... 

`sequential/test-child-process-fork-getconnections` on alpine-last-latest-x64.. I think that might be a flake

` test.es-module/test-esm-symlink-type` on windows

```
AssertionError [ERR_ASSERTION]: For {"source":"extensionless-symlink-to-mjs-file","prints":".mjs file","errorsWithPreserveSymlinksMain":false}, errored unexpectedly with --preserve-symlinks-main
    at common.mustCall (c:\workspace\node-test-binary-windows\test\es-module\test-esm-symlink-type.js:56:18)
    at c:\workspace\node-test-binary-windows\test\common\index.js:367:15
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by MylesBorins** [comment]
We've ended up reverted #45 temporarily and moving it into this PR in an attempt to get CI green. We should like land as a single commit after we get it working

**Comment by MylesBorins** [comment]
CI of modules-lkgr for comparison: https://ci.nodejs.org/job/node-test-commit/26374/

**Comment by MylesBorins** [comment]
hmmm I'm actually seeing a bunch more failures on LKGR before that other Pr... fun!

I'm going to go ahead and land this as it is

@guybedford lets dig into and try to find the windows fix independently and worry about making the branch release ready later

**Pull request merged**
