### PR TITLE
Remove default ".json" and ".node" resolution for ESM

### PR DESCRIPTION
**Pull request by guybedford**
In line with simplifying towards browser compatibility, this removes the default resolution of ".json" files from ESM (although ".json" can still be resolved from CommonJS of course).

Custom loaders could still add this back as the "json" translator is still defined though here.

Looking forward to the browser compatibility discussion :)

edit (@mylesborins): I've also added the removal of .node to this PR.

### CODE REVIEW

**Comment by devsnek** [comment]
> Custom loaders could still add this back as the "json" translator is still defined though here.

custom loaders should do this themselves. the translator is just dead code now.

**Comment by guybedford** [comment]
Agreed they can do it through instantiate, ok I've added another commit to remove the translator entirely as well.

**Comment by Janpot** [comment]
@ljharb Isn't the point of this fork to just create a "minimal kernel" as a starting point, so that further features can be layered on through PRs and so there is actually something tangible to discuss about those?

**Comment by ljharb** [comment]
@Janpot yes, but that requires consensus on what "minimal" means, and I don't think a minimal kernel is one that lacks the basic and core feature of resolution that already exists in node.

**Comment by MylesBorins** [comment]
I've added the removal of .node to the PR to align with the currently proposed minimal kernel. removing  cjs support will come in a future push once createRequire function has landed upstream

**Comment by MylesBorins** [comment]
Closing in lieu of https://github.com/nodejs/ecmascript-modules/pull/6

**Pull request closed without merging**
