### PR TITLE
Revert "esm: Remove --experimental-vm-modules."

### PR DESCRIPTION
**Pull request by devsnek**
This reverts commit e8453324418b3153af78b1f111fe133598bb7556.

Continuation of #7

cc @jdalton @zenparsing @MylesBorins @jkrems

### CODE REVIEW

**Comment by jdalton** [comment]
It looks like a rebase of some kind got pushed to master branch.

**Comment by devsnek** [comment]
@jdalton yeah i rebase nodejs/node into this repo roughly once a day. i have been meaning but continually forgetting to ask @targos if he has any ideas about how to streamline this based on his experience with keeping the nodejs/node-v8 repo.

in any case `source_text_module.js` exists in our source anyway because of upstream changes, and it isn't exposed, so i think this pr is useless now.

**Comment by jdalton** [comment]
Is this rebase activity covered somewhere in the ecmascript-modules docs?

**Comment by devsnek** [comment]
@jdalton I'm not sure what you mean

**Comment by jdalton** [comment]
I mean normally there's a pretty defined process for how folks interact with repos in the Node org. This is a shared space, not personal sandbox, so unless you've been given special permission by the WG to perform these rebases/merges/commits I'd ask that you stop until there is such process in place.

**Pull request closed without merging**
