### PR TITLE
Revert "esm: Remove --experimental-vm-modules."

### PR DESCRIPTION
**Pull request by devsnek**
This reverts commit c9dafb9b7155f32cb1f12e638035c39bca53d454.

cc @nodejs/modules 

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

**Comment by devsnek** [comment]
@jdalton i'm not quite sure i understand the reasoning for removing this... All it does is wrap the c++ `ModuleWrap` class, (and from a maintainability standpoint this removal is already causing merge issues with nodejs/node)

**Comment by devsnek** [comment]
CI https://ci.nodejs.org/job/node-test-pull-request/17631/

**Comment by jdalton** [comment]
As mentioned https://github.com/nodejs/modules/pull/180#pullrequestreview-161213066 
>  I see `--experimental-vm-modules` as extra and not critical for a minimal barebones implementation. That's not to say anything needed for internal minimal functionality couldn't stay, just that the user facing bits can probably be dropped.

Could you tweak this PR in a way so that the external bits _(the flag, external API)_ can be dropped?

**Comment by MylesBorins** [comment]
@jdalton if we can reach consensus that we want to add VM support in phase 2 could this land as is? Do you have specific objections to VM support?

**Comment by devsnek** [comment]
@jdalton by the same argument should we remove http and crypto? i don't understand why vm is being singled out here.

**Comment by jdalton** [comment]
@devsnek Unlike `http` and `crypto` the `--experimental-vm-modules` is related to exposing API for the creation-and-wiring up of ES modules. It's something that isn't necessary for a minimal core and can be rethought or shaped further as we progress through the next phases.

**Comment by jkrems** [comment]
One example: I'm currently experimenting with a version of `ModuleWrap` that's not compiling on construction and doesn't use async functions for dependency resolution. So this API might become really awkward to support going forward if that becomes a thing.

**Comment by jdalton** [comment]
@MylesBorins 
> can you expand on how you imagine its shape could change?

I believe vm primitives can be shaped by and also shape the loader implementation. @zenparsing has some thoughts on it that we should explore.

**Comment by zenparsing** [comment]
Honestly, I'm still exploring this space (and catching up). The vm.SourceTextModule API looks pretty solid, but I think we should be open to taking it slow, experimenting, and not committing to all of the details just yet.

@jdalton 's suggestion 

> Could you tweak this PR in a way so that the external bits (the flag, external API) can be dropped?

seems fine as well.

**Pull request merged**
