### PR TITLE
Modules rebase

### PR DESCRIPTION
**Pull request by MylesBorins**
Tests work on this branch locally. We are going to have to force push against master.

The conflicts were not a huge deal, mostly related to the change in the way options or retrieved

### CODE REVIEW

**Comment by guybedford** [comment]
Nice work, could you bring node master through as a branch here so we can see the PR comparison of just our commits?

**Comment by guybedford** [comment]
(unfortunately because this is not a public fork that can't be done from GitHub compare otherwise)

**Comment by MylesBorins** [comment]
@guybedford I've gone ahead and reset master against upstream and pushed the last known good version of the master branch from this repo to `modules-lkgr`. I've also gone ahead and made that the default branch of the repo

This PR is now showing only the changes ontop of the current upstream master

**Comment by MylesBorins** [comment]
If CI is green I'm going to go ahead and force push and land the other PRs

**Comment by MylesBorins** [comment]
updated

**Pull request closed without merging**
