### PR TITLE
another conflict

### PR DESCRIPTION
**Pull request by MylesBorins**
specifically conflict with changes to `src/node_config.cc`

### CODE REVIEW

**Comment by MylesBorins** [comment]
CI: https://ci.nodejs.org/job/node-test-pull-request/19181/

**Comment by targos** [comment]
Is there a GitHub URL that we could use to see what the conflict was?

**Comment by MylesBorins** [comment]
TBH I'm unsure how to provide that.

**Comment by MylesBorins** [comment]
Looks like a whole bunch of stuff broke with this rebase... I'm digging in

**Comment by MylesBorins** [comment]
windows is known flake. Documented in https://github.com/nodejs/node/issues/24403#issuecomment-444296611

**Comment by MylesBorins** [comment]
landed in 83ee137c45...7bf886a2e6

**Pull request closed without merging**
